name: Deploy Worker (main branch)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      # Secrets stored in github
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          environment: main
          secrets: |
            API_TOKEN
        env:
          API_TOKEN: ${{ env.API_TOKEN }}
